# Generated by Django 5.1.1 on 2024-10-14 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_description_is_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.description')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.place')),
            ],
            options={
                'unique_together': {('place', 'description')},
            },
        ),
    ]
