version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    environment:
      POSTGRES_DB: aroundmego_db
      POSTGRES_USER: aroundmego_admin
      POSTGRES_PASSWORD: 21233
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./aroundmego:/app  # Монтируем папку с manage.py
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: super_secret_django_key_here
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: aroundmego_db
      DB_USER: aroundmego_admin
      DB_PASSWORD: 21233
      DB_HOST: db
      DB_PORT: 5432
    env_file:
      - .env

volumes:
  postgres_data:
